sudo: required
language: c
install: sudo apt-get install -qq -y --no-install-recommends libpam0g-dev
before_script: autoreconf -f -i
script: ./configure && make --with-pam-mods-dir=./build && make test