sudo: required
language: c
install: sudo apt-get install -qq -y --no-install-recommends libpam0g-dev
before_script: autoreconf -f -i
script: ./configure --with-pam-mods-dir=${TRAVIS_BUILD_DIR}/build && make && cat Makefile